### ISSUE TITLE
[Epic] reproduce Cabbage GUI widgets for Rack

### ISSUE THREAD

**Issue by brylie** [rorywalsh/CabbageRack#3]
Currently, only a subset of Cabbage widgets have been reproduced for Rack. This is mainly due to the work involved in creating GUI widgets in two different frameworks.

This issue can serve as a roadmap, of sorts, to identify widgets that aren't supported by CabbageRack and prioritize development.

## Task

- [ ] identify which GUI frameworks are used by Cabbage and Rack respectively
- [ ] add links to GUI framework documentation in contributing guide
- [ ] identify which GUI widgets have not been recreated in CabbageRack (list below)
- [ ] prioritize the list (by dragging list items into priority order) based on a ration of `usefulness` / `development complexity`
   - or is it `development complexity` / `usefulness`? 
   - `usefulness` ** `development complexity`? :rocket: 

## Widget list
The following list tracks progress to re*produce* :leafy_green:  each Cabbage widget for VCV

- [ ] [Button](https://cabbageaudio.com/docs/button/)
- [ ] [Button (File button)](https://cabbageaudio.com/docs/button_file/)
- [ ] [Button (Information button)](https://cabbageaudio.com/docs/button_info/)
- [ ] [OptionButton](https://cabbageaudio.com/docs/button_option/)
- [ ] [Check Box](https://cabbageaudio.com/docs/checkbox/)
- [ ] [Combo Box](https://cabbageaudio.com/docs/combobox/)
- [ ] [Csound Output Widget](https://cabbageaudio.com/docs/csound_output/)
- [ ] [Endless encoder](https://cabbageaudio.com/docs/encoder/)
- [ ] [Form](https://cabbageaudio.com/docs/form/)
- [ ] [GenTable](https://cabbageaudio.com/docs/gentable/)
- [ ] [Group Box](https://cabbageaudio.com/docs/groupbox/)
- [ ] [Image](https://cabbageaudio.com/docs/image/)
- [ ] [Keyboard](https://cabbageaudio.com/docs/keyboard/)
- [ ] [Label](https://cabbageaudio.com/docs/label/)
- [ ] [List box](https://cabbageaudio.com/docs/listbox/)
- [ ] [Meter](https://cabbageaudio.com/docs/meter/)
- [ ] [Signal Display](https://cabbageaudio.com/docs/signaldisplay/)
- [ ] [Sliders](https://cabbageaudio.com/docs/sliders/)
- [ ] [Soundfiler](https://cabbageaudio.com/docs/soundfiler/)
- [ ] [Text Editor](https://cabbageaudio.com/docs/texteditor/)
- [ ] [XY Pad](https://cabbageaudio.com/docs/xypad/)
